name: Staging CI

on:
  push:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Save original git author and git email
        run: |
          echo "git_email=$(git log --format='%ae' HEAD^!)" >> $GITHUB_ENV
          echo "git_name=$(git log --format='%an' HEAD^!)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Change homepage in package.json
        run: sed -i 's/place-holder/OATutor-Staging/g' package.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_BUILD_TYPE: "platform-staging"
          REACT_APP_MIDDLEWARE_URL: ${{ secrets.STAGING_MIDDLEWARE_URL }}
          REACT_APP_OPENROUTER_WORKER_URL: ${{ secrets.OPENROUTER_WORKER_URL }}
          REACT_APP_COMMIT_HASH: ${{ github.sha }}

      - uses: actions/checkout@v4
        with:
          repository: 'CAHLR/OATutor-Staging'
          ssh-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          ref: 'main'
          path: 'staging-build'

      - name: Push
        run: |
          cd staging-build
          git rm -rf .
          git clean -fxd
          rsync -a ../build/ .
          git add .
          git config --local user.email "${{ env.git_email }}"
          git config --local user.name "${{ env.git_name }}"
          git diff --cached --quiet --exit-code && echo "no changes to platform, exiting early" && exit 0
          git commit -m "deploy commit: CAHLR/OATutor@$GITHUB_SHA"
          git push
